# Generated by Django 6.1 on 2026-08-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='password',
            field=models.CharField(default='temporary', max_length=24),
            preserve_default=False,
        ),
    ]
